site_name: Lucy Wisteria's Notebook
site_description: A notebook for Lucy Wisteria
site_author: Lucy Wisteria
repo_name: wsh-zju/notebook
site_url: https://wsh-zju.github.io/notebook/
repo_url: https://github.com/wsh-zju/notebook
edit_uri: tree/main/docs
copyright: Copyright &copy; 2024 - (｡･ω･｡)ﾉ Lucy Wisteria


theme: 
  name: 'material'
  custom_dir: overrides
  language: 'zh'
  logo: style/images/logo.png
  favicon: style/images/favicon_io/favicon.ico
  features:
    - favicon.ico
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    ##- navigation.expand   #页面默认展开
    - navigation.footer
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
      admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - toc:
      permalink: true      # 目录标题添加锚点
      toc_depth: 4         # 目录显示到4级标题
  - abbr                   # 支持缩写
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition             # 支持警告/提示块(!!!/???)
  - pymdownx.keys          # 按键
  - pymdownx.mark          # 高亮（==高亮==）
  - pymdownx.tilde         # 支持删除线/下标（~~删除线~~/^^下标^^）
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["docs"]  # 告诉插件在 docs 目录找文件
      check_paths: true    # 找不到文件时会在终端报错
      auto_append:
        - terms.md
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true      # 显示行号
      auto_title: true    # 显示编程语言
  - pymdownx.arithmatex:
      generic: true
  

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore


plugins:
    - mermaid2
    - search
    #- heti:
        #extra_skipped_class:
          #- arithmatex
    - macros
    - git-revision-date-localized:
        enable_git_follow: true
        enable_creation_date: true  # 开启创建时间
        type: datetime              # 显示格式（包含具体时间）
        timezone: Asia/Shanghai     # 设置为中国时区
        locale: zh
        exclude:
            - 'index.md'  # 首页不显示修改时间
            - '**/index.md'  # 各目录的index.md不显示修改时间
            - '**/**/index.md'  # 多层目录的index.md不显示修改时间

hooks:
  - hooks/toc.py
  - hooks/static.py

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://npm.elemecdn.com/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css     # FontAwesome 
  - style/css/tasklist.css
  - style/css/home_card.css
  - style/css/custom.css
  - style/css/card.css
  - style/css/flink.css
  - style/css/toc_extra.css
  - style/css/svg_extra.css
  - style/css/counter.css
  - style/css/english.css
  - style/css/riscv.css
  - style/css/search.css
  - style/css/weixin.css


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - style/js/mathjax.js
  

nav:
  - 首页: 
    - index.md
    - 公众号 : 
      - weixin/index.md
      - macOS 终端 : weixin/macos.md
      - 六级词汇 : weixin/cet6-cihui.md
      - 六级翻译 : weixin/cet6-fanyi.md
  - 计算机类课程 :
    - Computer_Science/index.md
    - 计算机系统 :
      - Computer_Science/Computer_System/index.md
      - 数据编码 : Computer_Science/Computer_System/data.md
      - 数字逻辑基础 : Computer_Science/Computer_System/logic.md
      - 组合逻辑电路 : Computer_Science/Computer_System/combine.md
      - 运算单元 : Computer_Science/Computer_System/ALU.md
      - 时序逻辑电路 : Computer_Science/Computer_System/sequence.md
      - ISA : Computer_Science/Computer_System/ISA.md
      - CPU : Computer_Science/Computer_System/CPU.md
      - 多周期CPU : Computer_Science/Computer_System/MultiCPU.md
      - 流水线CPU : Computer_Science/Computer_System/pipeline.md
      - 操作系统 : 
        - 操作系统 : Computer_Science/Computer_System/OS.md
        - 进程 : Computer_Science/Computer_System/process.md
        - IPC : Computer_Science/Computer_System/IPCs.md
        - CPU 调度 : Computer_Science/Computer_System/schedule.md
        - 线程 : Computer_Science/Computer_System/thread.md
        - 同步 : Computer_Science/Computer_System/synch.md
        - 死锁 : Computer_Science/Computer_System/deadlock.md
      - 量化研究方法 : Computer_Science/Computer_System/quant.md
      - 指令级并行 : Computer_Science/Computer_System/ILP.md
      - 内存 : 
        - 内存层次结构 : Computer_Science/Computer_System/memory_index.md
        - 缓存 : Computer_Science/Computer_System/cache.md
        - 主存 : Computer_Science/Computer_System/main_memory.md
    - 数据结构与算法分析 :
      - Computer_Science/Data_Structure/index.md
      - FDS :
        - Computer_Science/Data_Structure/Foundation/index.md
        - 线性数据结构 : Computer_Science/Data_Structure/Foundation/Linear.md
        - 树 : Computer_Science/Data_Structure/Foundation/Tree.md
        - 堆 : Computer_Science/Data_Structure/Foundation/Heap.md
        - 不相交集ADT : Computer_Science/Data_Structure/Foundation/ADT.md
        - 图 : Computer_Science/Data_Structure/Foundation/Graph.md
        - 排序 : Computer_Science/Data_Structure/Foundation/Sort.md
        - 哈希 : Computer_Science/Data_Structure/Foundation/Hash.md
        - PTA : Computer_Science/Data_Structure/Foundation/pta.md
      - ADS :
        - Computer_Science/Data_Structure/Advanced/index.md 
        - 树 : Computer_Science/Data_Structure/Advanced/tree.md
        - 堆 : Computer_Science/Data_Structure/Advanced/heap.md
        - 队列 : Computer_Science/Data_Structure/Advanced/queue.md
        - 摊还分析 : Computer_Science/Data_Structure/Advanced/amort.md
        - 倒排索引 : Computer_Science/Data_Structure/Advanced/inv.md
        - 回溯算法 : Computer_Science/Data_Structure/Advanced/back.md
        - 分而治之 : Computer_Science/Data_Structure/Advanced/divide.md
        - 动态规划 : Computer_Science/Data_Structure/Advanced/DP.md
        - 贪心算法 : Computer_Science/Data_Structure/Advanced/greedy.md
        - NP完全性 : Computer_Science/Data_Structure/Advanced/NP.md
        - 近似算法 : Computer_Science/Data_Structure/Advanced/appro.md
        - 局部搜索 : Computer_Science/Data_Structure/Advanced/localsearch.md
        - 随机化算法 : Computer_Science/Data_Structure/Advanced/random.md
        - 并行算法 : Computer_Science/Data_Structure/Advanced/paral.md
        - 外部排序 : Computer_Science/Data_Structure/Advanced/exter.md
        - PTA : Computer_Science/Data_Structure/Advanced/pta.md
    - 人工智能引论 : Computer_Science/AI.md
    - 数据库系统 : 
      - Computer_Science/Database_System/index.md
      - 基本介绍 : Computer_Science/Database_System/introduce.md
      - 关系模型 : Computer_Science/Database_System/relationmodel.md
      - E-R 模型 : Computer_Science/Database_System/E-R.md
      - SQL 语言 :
        - SQL 基础 : Computer_Science/Database_System/sql_found.md 
        - SQL 进阶 : Computer_Science/Database_System/sql_adv.md
      - 关系数据库设计 : Computer_Science/Database_System/relationdb.md 
      - 存储与文件结构 : Computer_Science/Database_System/store&file.md
  - 开发工具 :
    - Tools/index.md
    - C :
      - Tools/C/index.md
      - 指针 : Tools/C/pointer.md
      - 递归与迭代 : Tools/C/recursion.md
      - 程序结构 : Tools/C/structure.md
      - 文件底层操作 : Tools/C/file.md
      - 常用知识汇总 : Tools/C/accumulate.md
    - C++ :
      - Tools/C++/index.md
      - 对象 : Tools/C++/object.md
      - 容器 : Tools/C++/container.md
      - 类 : Tools/C++/class.md
      - 复用 : Tools/C++/reuse.md
      - 多态 : Tools/C++/polymorphism.md
      - PTA : Tools/C++/pta.md
    - Python :
      - Tools/Python/index.md
      - 基础语法 : Tools/Python/foundation.md
      - 数据类型 : Tools/Python/data.md
      - 进阶语法 : Tools/Python/advance.md
      - 常用知识汇总 : Tools/Python/accumulate.md
    - Verilog :
      - Tools/Verilog.md
    - CSS : Tools/Css.md
    - mkdocs 配置: 
      - Tools/mkdocs/index.md
      - 主题 : Tools/mkdocs/theme.md
    - Latex 语法 : Tools/Latex.md
    - 终端常用命令 : Tools/terminal.md
  - 其余课程 :
    - Others/index.md
    - 数理课程 : 
      - Others/Math_and_Physics/index.md
      - 离散数学理论基础 :
        - Others/Math_and_Physics/Discrete_Mathematics/index.md
        - 逻辑与证明: Others/Math_and_Physics/Discrete_Mathematics/chapter1.md
        - 基本结构: Others/Math_and_Physics/Discrete_Mathematics/chapter2.md
        - 算法: Others/Math_and_Physics/Discrete_Mathematics/chapter3.md
        - 数论: Others/Math_and_Physics/Discrete_Mathematics/chapter4.md
        - 归纳与递归: Others/Math_and_Physics/Discrete_Mathematics/chapter5.md
        - 计数: Others/Math_and_Physics/Discrete_Mathematics/chapter6.md
        - 高级计数: Others/Math_and_Physics/Discrete_Mathematics/chapter8.md
        - 关系 : Others/Math_and_Physics/Discrete_Mathematics/chapter9.md
        - 图: Others/Math_and_Physics/Discrete_Mathematics/chapter10.md
        - 树: Others/Math_and_Physics/Discrete_Mathematics/chapter11.md
    - 思政课程 :
      - 马克思主义基本原理 : Others/sizheng/mayuan.md
      - 毛泽东思想和中国特色社会主义理论体系概论 : Others/sizheng/maogai.md
      - 习近平新时代中国特色社会主义思想概论 : Others/sizheng/xigai.md
