site_name: Lucy Wisteria's Notebook
site_description: A notebook for Lucy Wisteria
site_author: Lucy Wisteria
repo_name: wsh-zju/notebook
site_url: https://wsh-zju.github.io/notebook/
repo_url: https://github.com/wsh-zju/notebook
edit_uri: tree/main/docs
copyright: Copyright &copy; 2024 - (｡･ω･｡)ﾉ LucyWisteria

nav:
  - Home: 
    - index.md
  - Computer Science :
    - 编程语言 :
      - Computer_Science/Language/index.md
      - C 语言 :
        - Computer_Science/Language/C/index.md
        - 指针 : Computer_Science/Language/C/pointer.md
        - 递归与迭代 : Computer_Science/Language/C/recursion.md
        - 程序结构 : Computer_Science/Language/C/structure.md
        - 文件底层操作 : Computer_Science/Language/C/file.md
        - 常用知识汇总 : Computer_Science/Language/C/accumulate.md
      - Python :
        - Computer_Science/Language/Python/index.md
        - 基础语法 : Computer_Science/Language/Python/foundation.md
        - 数据类型 : Computer_Science/Language/Python/data.md
        - 进阶语法 : Computer_Science/Language/Python/advance.md
        - 常用知识汇总 : Computer_Science/Language/Python/accumulate.md
      - CSS : Computer_Science/Language/Css.md
    - 计算机系统 :
      - Computer_Science/Computer_System/index.md
      - 数据编码 : Computer_Science/Computer_System/data.md
      - 数字逻辑基础 : Computer_Science/Computer_System/logic.md
      - 组合逻辑电路 : Computer_Science/Computer_System/combine.md
      - 运算单元 : Computer_Science/Computer_System/ALU.md
      - 时序逻辑电路 : Computer_Science/Computer_System/sequence.md
      - ISA : Computer_Science/Computer_System/ISA.md
      - CPU : Computer_Science/Computer_System/CPU.md
      - 多周期CPU : Computer_Science/Computer_System/MultiCPU.md
      - 流水线CPU : Computer_Science/Computer_System/pipeline.md
      - 操作系统 : Computer_Science/Computer_System/OS.md
      - 进程 : Computer_Science/Computer_System/process.md
      - CPU 调度 : Computer_Science/Computer_System/schedule.md
      - 实验 : Computer_Science/Computer_System/lab.md
    - 数据结构 :
      - FDS :
        - Computer_Science/Data_Structure/Foundation/index.md
        - 线性数据结构 : Computer_Science/Data_Structure/Foundation/Linear.md
        - 树 : Computer_Science/Data_Structure/Foundation/Tree.md
        - 堆 : Computer_Science/Data_Structure/Foundation/Heap.md
        - 不相交集ADT : Computer_Science/Data_Structure/Foundation/ADT.md
        - 图 : Computer_Science/Data_Structure/Foundation/Graph.md
        - 排序 : Computer_Science/Data_Structure/Foundation/Sort.md
        - 哈希 : Computer_Science/Data_Structure/Foundation/Hash.md
        - PTA : Computer_Science/Data_Structure/Foundation/pta.md
      - ADS :
        - Computer_Science/Data_Structure/Advanced/index.md 
        - 树 : Computer_Science/Data_Structure/Advanced/tree.md
        - 堆 : Computer_Science/Data_Structure/Advanced/heap.md
        - 队列 : Computer_Science/Data_Structure/Advanced/queue.md
        - 摊还分析 : Computer_Science/Data_Structure/Advanced/amort.md
        - 倒排索引 : Computer_Science/Data_Structure/Advanced/inv.md
        - 回溯算法 : Computer_Science/Data_Structure/Advanced/back.md
        - 分而治之 : Computer_Science/Data_Structure/Advanced/divide.md
        - 动态规划 : Computer_Science/Data_Structure/Advanced/DP.md
        - 贪心算法 : Computer_Science/Data_Structure/Advanced/greedy.md
        - NP完全性 : Computer_Science/Data_Structure/Advanced/NP.md
        - 近似算法 : Computer_Science/Data_Structure/Advanced/appro.md
        - 局部搜索 : Computer_Science/Data_Structure/Advanced/localsearch.md
        - 随机化算法 : Computer_Science/Data_Structure/Advanced/random.md
        - 并行算法 : Computer_Science/Data_Structure/Advanced/paral.md
        - PTA : Computer_Science/Data_Structure/Advanced/pta.md
  - Math and Physics : 
    - Math_and_Physics/index.md
    - 离散数学理论基础 :
      - Math_and_Physics/Discrete_Mathematics/index.md
      - 逻辑与证明: Math_and_Physics/Discrete_Mathematics/chapter1.md
      - 基本结构: Math_and_Physics/Discrete_Mathematics/chapter2.md
      - 算法: Math_and_Physics/Discrete_Mathematics/chapter3.md
      - 数论: Math_and_Physics/Discrete_Mathematics/chapter4.md
      - 归纳与递归: Math_and_Physics/Discrete_Mathematics/chapter5.md
      - 计数: Math_and_Physics/Discrete_Mathematics/chapter6.md
      - 高级计数: Math_and_Physics/Discrete_Mathematics/chapter8.md
      - 关系 : Math_and_Physics/Discrete_Mathematics/chapter9.md
      - 图: Math_and_Physics/Discrete_Mathematics/chapter10.md
      - 树: Math_and_Physics/Discrete_Mathematics/chapter11.md
  - Tools :
    - tool/index.md
    - mkdocs : 
      - 主题 : tool/mkdocs/theme.md
    - Latex : 
      - 语法 : tool/latex/Latex.md
  
  
  

theme: 
  name: 'material'
  language: 'zh'
  logo: style/images/logo.png
  favicon: style/images/favicon_io/favicon.ico
  features:
    - favicon.ico
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    ##- navigation.expand   #页面默认展开
    - navigation.footer
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
  font:
      code: JetBrains Mono
      text: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
      admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - toc:
      permalink: true      # 目录标题添加锚点
      toc_depth: 4         # 目录显示到4级标题
  - abbr                   # 支持缩写
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition             # 支持警告/提示块(!!!/???)
  - pymdownx.keys          # 按键
  - pymdownx.mark          # 高亮（==高亮==）
  - pymdownx.tilde         # 支持删除线/下标（~~删除线~~/^^下标^^）
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true      # 显示行号
      auto_title: true    # 显示编程语言名称
  - pymdownx.arithmatex:
      generic: true
  

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

plugins:
  - mermaid2
  - search
  #- heti:
      #extra_skipped_class:
        #- arithmatex
  - macros


extra_css:
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.jsdelivr.net/npm/asana-math@1.0/fonts/asana-math.css
  - style/css/tasklist.css
  - style/css/custom.css
  - style/css/card.css
  - style/css/flink.css
  - style/css/changelog_extra.css
  - style/css/toc_extra.css
  - style/css/svg_extra.css
  - style/css/counter.css


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js